// Live Signals screen (UI spec 11.1).

import type { ReactElement } from 'react';
import { PageShell } from '../../shell/PageShell';

export function TradingSignalsPage(): ReactElement {
  return (
    <PageShell
      title="Live Strategy Signals"
      description="Real-time buy/sell triggers generated by approved strategies"
      breadcrumbs={[{ label: 'Overview', to: '/overview' }, { label: 'Signals' }]}
    >
      <div
        style={{
          padding: 'var(--space-4)',
          backgroundColor: 'var(--surface-raised)',
          borderRadius: 'var(--radius-md)',
          border: 'var(--border-width-thin) solid var(--border-subtle)',
        }}
      >
        <p style={{ color: 'var(--text-secondary)' }}>
          Generated signal stream with confidence scores and proposed order sizing.
        </p>
      </div>
    </PageShell>
  );
}
